name: Build ESP32 Marauder - Cheap Yellow Display

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build_cyd:
    name: Build CYD ${{ matrix.board.flag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - { name: "Cheap Yellow Display 2.2", flag: "CYD_22CAP", fbqn: "esp32:esp32:lolin32", build_dir: "lolin32" }
          - { name: "Cheap Yellow Display 2.4", flag: "CYD_24", fbqn: "esp32:esp32:lolin32", build_dir: "lolin32" }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: esp32-marauder-src

      - name: Set working directory
        run: echo "ESP32_MARAUDER_WORKDIR=$(pwd)/esp32-marauder-src" >> $GITHUB_ENV

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$GITHUB_ENV/bin" >> $GITHUB_PATH
          export PATH="$GITHUB_ENV/bin:$PATH"
          arduino-cli version

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.10

      - name: Verify Installed Cores
        run: arduino-cli core list

      - name: Select CYD variant in configs.h
        run: |
          cd "$ESP32_MARAUDER_WORKDIR"
          sed -i 's/^[[:space:]]*#define CYD_\([^ ]*\)/\/\/\0/' esp32_marauder/configs.h
          sed -i "s/^\([[:space:]]*\)\/\/[[:space:]]*#define ${{ matrix.board.flag }}/\1#define ${{ matrix.board.flag }}/" esp32_marauder/configs.h

      - name: Install libraries from libraries folder
        run: |
          mkdir -p $HOME/Arduino/libraries
          cp -r "$ESP32_MARAUDER_WORKDIR"/libraries/* $HOME/Arduino/libraries/

      - name: List installed Arduino libraries
        run: arduino-cli lib list

      - name: Compile with ArminJo/arduino-test-compile
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: esp32_marauder/esp32_marauder.ino
          sketch-names-find-start: esp32-marauder-src
          arduino-board-fqbn: ${{ matrix.board.fbqn }}
          extra-arduino-cli-args: "--warnings none"
          arduino-platform: esp32:esp32@2.0.10
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Rename binary with version and date
        run: |
          cd "$ESP32_MARAUDER_WORKDIR"
          VERSION=$(grep 'MARAUDER_VERSION' esp32_marauder/esp32_marauder.ino | cut -d '"' -f2 | tr '.' '_')
          DATE=$(date +%Y%m%d)
          BINFILE=$(find ~/.arduino15/packages/esp32/hardware/esp32/*/build -name '*.bin' | head -n1 || find esp32_marauder/build -name '*.bin' | head -n1)
          OUTFILE="esp32_marauder_${VERSION}_${DATE}_${{ matrix.board.flag }}.bin"
          cp "$BINFILE" "$OUTFILE"
          echo "OUTFILE=$OUTFILE" >> $GITHUB_ENV

      - name: Upload renamed artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTFILE }}
          path: ${{ env.OUTFILE }}