name: Build ESP32 Marauder - Cheap Yellow Display

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build_cyd:
    name: Build CYD ${{ matrix.board.flag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - name: "Cheap Yellow Display 2.2"
            flag: "CYD_22CAP"
            fbqn: "esp32:esp32:lolin32"
            build_dir: "lolin32"
            libs:
              - "adafruit/Adafruit_BusIO@1.17.0"
              - "adafruit/Adafruit_CPFS@1.1.0"
              - "adafruit/Adafruit-GFX-Library@1.12.0"
              - "adafruit/Adafruit_ILI9341@1.6.0"
              - "adafruit/Adafruit_InternalFlash@0.1.1"
              - "adafruit/Adafruit_IS31FL3731@2.0.2"
              - "adafruit/Adafruit_MAX1704X@1.0.3"
              - "adafruit/Adafruit_NeoPixel@1.12.4"
              - "adafruit/Adafruit_SH110x@2.1.10"
              - "adafruit/Adafruit_SPIFlash@5.0.1"
              - "adafruit/Adafruit_STMPE610@1.1.6"
              - "adafruit/Adafruit_TinyUSB_Arduino@3.4.2"
              - "adafruit/Adafruit_TouchScreen@1.1.5"
              - "adafruit/Adafruit_TSC2007@1.1.2"
              - "nopnop2002/Arduino-LoRa-Ra01S@1.0.0"
              - "bblanchon/ArduinoJson@6.21.4"
              - "bitbank2/bb_captouch@1.2.2"
              - "bitbank2/bb_spi_lcd@2.9.1"
              - "me-no-dev/ESPAsyncWebServer@2.10.4"
              - "earlephilhower/ESP32-audioI2S@2.0.0"
              - "felmue/ESP32Time@2.0.4"
              - "dvarrel/ESPAsyncWebSrv@1.2.9"
              - "PaulStoffregen/SoftwareSerial@8.1.0"
              - "Arduino-FOC/FlashStorage@1.0.0"
              - "moononournation/Arduino_GFX@1.2.9"
              - "PaulStoffregen/ILI9341_t3@1.0"
              - "Bodmer/JPEGDecoder@2.0.0"
              - "ivanseidel/LinkedList@1.3.3"
              - "lorol/LITTLEFS@1.0.6"
              - "lovyan03/LovyanGFX@1.1.9"
              - "lvgl/lv_arduino@3.0.1"
              - "stevemarple/MicroNMEA@2.0.6"
              - "FortySevenEffects/arduino_midi_library@5.0.2"
              - "h2zero/NimBLE-Arduino@1.3.5"
              - "arduino-libraries/NTPClient@3.2.1"
              - "adafruit/Adafruit_PicoDVI@1.3.0"
              - "adafruit/SdFat@2.2.3"
              - "olikraus/U8g2@2.35.30"
              - "libraries/SensorLib@0.2.2"
              - "libraries/SwitchLib@1.1.1"
              - "libraries/TAMC_GT911@1.0.2"
              - "libraries/ThingPulse_XPT2046_Touch@latest"
              - "libraries/Touch_GT911@latest"
              - "libraries/Arduino-Ra01S@latest"
              - "libraries/TFT_eSPI-CYD/2.2C/TFT_eSPI@latest"
              - "libraries/ESPAsyncWebServer@latest"
              - "libraries/ESP32-audioI2S-master@latest"
              - "libraries/ESP32Time@latest"
              - "libraries/EspSoftwareSerial@latest"
              - "libraries/FlashStorage@latest"
              - "libraries/Adafruit_GFX_Library@latest"
              - "libraries/LinkedList@latest"
              - "libraries/MicroNMEA@latest"
              - "libraries/MIDI_Library@latest"
              - "libraries/AsyncTCP@latest"
              - "libraries/PicoDVI_-_Adafruit_Fork@latest"


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: esp32-marauder-src

      - name: Set working directory
        run: echo "ESP32_MARAUDER_WORKDIR=$(pwd)/esp32-marauder-src" >> $GITHUB_ENV

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH
          echo "PATH=$PWD/bin:$PATH" >> $GITHUB_ENV
          ./bin/arduino-cli version

      - name: Install ESP32 Core
        run: |
          ./bin/arduino-cli core update-index
          ./bin/arduino-cli core install esp32:esp32@2.0.10

      - name: Verify Installed Cores
        run: ./bin/arduino-cli core list

      - name: Select CYD variant in configs.h
        run: |
          cd "$ESP32_MARAUDER_WORKDIR"
          sed -i 's/^[[:space:]]*#define CYD_\([^ ]*\)/\/\/\0/' esp32_marauder/configs.h
          sed -i "s/^\([[:space:]]*\)\/\/\s*#define ${{ matrix.board.flag }}/\1#define ${{ matrix.board.flag }}/" esp32_marauder/configs.h

      - name: Install required libraries from GitHub
        run: |
          mkdir -p $HOME/Arduino/libraries
          cd $HOME/Arduino/libraries
          for LIB in ${{ join(matrix.board.libs, ' ') }}; do
            REPO=$(echo "$LIB" | cut -d@ -f1)
            VERSION=$(echo "$LIB" | cut -d@ -f2)
            REL_PATH="${REPO#libraries/}"
            LIB_PATH="$ESP32_MARAUDER_WORKDIR/libraries/$REL_PATH"
            LIB_DEST="$HOME/Arduino/libraries/$(basename "$REL_PATH")"
            echo "Processing: $REPO@$VERSION"
            if [[ "$REPO" == libraries/* ]]; then
              if [[ -d "$LIB_PATH" ]]; then
                echo "Copying local library from $LIB_PATH to $LIB_DEST"
                cp -r "$LIB_PATH" "$LIB_DEST"
              else
                echo "::warning::Library path '$LIB_PATH' not found. Skipping."
              fi
            else
              echo "Checking if https://github.com/$REPO.git has $VERSION..."
              if git ls-remote --tags --heads https://github.com/$REPO.git | grep -q "refs/tags/$VERSION"; then
                echo "Cloning tag $VERSION from $REPO"
                git clone --depth 1 --branch "$VERSION" "https://github.com/$REPO.git" "$LIB_DEST"
              else
                echo "::warning::Tag '$VERSION' not found for $REPO. Skipping."
              fi
            fi
          done

      - name: List installed Arduino libraries
        run: ./bin/arduino-cli lib list

      - name: List all sketches before build
        run: |
          echo "Looking for .ino files in $ESP32_MARAUDER_WORKDIR..."
          find "$ESP32_MARAUDER_WORKDIR" -type f -name "*.ino"

      - name: Compile ${{ matrix.board.name }}
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: esp32_marauder.ino
          sketch-names-find-start: esp32-marauder-src
          arduino-board-fqbn: ${{ matrix.board.fbqn }}
          extra-arduino-cli-args: "--warnings none"
          arduino-platform: esp32:esp32@2.0.10
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Rename binary with version and date
        run: |
          cd "$ESP32_MARAUDER_WORKDIR"
          VERSION=$(grep 'MARAUDER_VERSION' esp32_marauder/esp32_marauder.ino | cut -d '"' -f2 | tr '.' '_')
          DATE=$(date +%Y%m%d)
          BINFILE=$(find ~/.arduino15/packages/esp32/hardware/esp32/*/build -name '*.bin' | head -n1 || find esp32_marauder/build -name '*.bin' | head -n1)
          OUTFILE="esp32_marauder_${VERSION}_${DATE}_${{ matrix.board.flag }}.bin"
          cp "$BINFILE" "$OUTFILE"
          echo "OUTFILE=$OUTFILE" >> $GITHUB_ENV

      - name: Upload renamed artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTFILE }}
          path: ${{ env.OUTFILE }}
