name: Build ESP32 Marauder - Cheap Yellow Display

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build_cyd:
    name: Build CYD ${{ matrix.board.flag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - name: "Cheap Yellow Display 2.2"
            flag: "CYD_24CAP"
            fbqn: "esp32:esp32:d32:PartitionScheme=min_spiffs"
            build_dir: "lolin32"
            libs:
              - "libraries/Adafruit_BusIO@latest"
              - "libraries/Adafruit_CPFS@latest"
              - "libraries/Adafruit_GFX_Library@latest"
              - "libraries/Adafruit_ILI9341@latest"
              - "libraries/Adafruit_InternalFlash@latest"
              - "libraries/Adafruit_IS31FL3731_Library@latest"
              - "libraries/Adafruit_MAX1704X@latest"
              - "libraries/Adafruit_NeoPixel@latest"
              - "libraries/Adafruit_SH110X@latest"
              - "libraries/Adafruit_SPIFlash@latest"
              - "libraries/Adafruit_STMPE610@latest"
              - "libraries/Adafruit_TinyUSB_Library@latest"
              - "libraries/Adafruit_TouchScreen@latest"
              - "libraries/Adafruit_TSC2007@latest"
              - "libraries/Arduino_GFX-master@latest"
              - "libraries/bb_spi_lcd@latest"
              - "libraries/ESPAsyncWebSrv@latest"
              - "libraries/ILI9341_t3@latest"
              - "libraries/JPEGDecoder@latest"
              - "libraries/LovyanGFX@1latest"
              - "libraries/lv_arduino@latest"
              - "libraries/NimBLE-Arduino@latest"
              - "libraries/NTPClient@latest"
              - "libraries/SdFat@latest"
              - "libraries/LittleFS_Mbed_RP2040@latest"
              - "libraries/U8g2@latest"
              - "libraries/SensorLib@latest"
              - "libraries/SwitchLib@latest"
              - "libraries/TAMC_GT911@latest"
              - "libraries/ThingPulse_XPT2046_Touch@latest"
              - "libraries/Touch_GT911@latest"
              - "libraries/Arduino-Ra01S@latest"
              - "libraries/TFT_eSPI-CYD/2.4C/TFT_eSPI@latest"
              - "libraries/ESPAsyncWebServer@latest"
              - "libraries/ESP32-audioI2S-master@latest"
              - "libraries/ESP32Time@latest"
              - "libraries/EspSoftwareSerial@latest"
              - "libraries/FlashStorage@latest"
              - "libraries/Adafruit_GFX_Library@latest"
              - "libraries/LinkedList@latest"
              - "libraries/MicroNMEA@latest"
              - "libraries/MIDI_Library@latest"
              - "libraries/AsyncTCP@latest"
              - "libraries/PicoDVI_-_Adafruit_Fork@latest"
              - "libraries/bb_captouch@latest"
              - "libraries/ArduinoJson@latest"
              - "libraries/ESPAsyncTCP@latest"
              - "libraries/ILI9341_t3-master@latest"
              - "libraries/LittleFS_esp32@latest"
              - "libraries/SdFat_-_Adafruit_Fork@latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: esp32-marauder-src

      - name: Set working directory
        run: echo "ESP32_MARAUDER_WORKDIR=$(pwd)/esp32-marauder-src" >> $GITHUB_ENV

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$PWD/bin" >> $GITHUB_PATH
          echo "PATH=$PWD/bin:$PATH" >> $GITHUB_ENV
          ./bin/arduino-cli version

      - name: Install ESP32 Core
        run: |
          ./bin/arduino-cli core update-index
          ./bin/arduino-cli core install esp32:esp32@2.0.10

      - name: Verify Installed Cores
        run: ./bin/arduino-cli core list

      - name: Select CYD variant in configs.h
        run: |
          cd "$ESP32_MARAUDER_WORKDIR"
          echo "Before modification:"
          grep -E '^\s*(//)?\s*#define CYD_' esp32_marauder/configs.h || echo "No CYD_ lines found"
          sed -i 's/^\([[:space:]]*\)#define CYD_/\1\/\/#define CYD_/' esp32_marauder/configs.h
          sed -i "s/^\([[:space:]]*\)\/\/#define ${{ matrix.board.flag }}/\1#define ${{ matrix.board.flag }}/" esp32_marauder/configs.h
          echo "After modification:"
          grep -E '^\s*(//)?\s*#define CYD_' esp32_marauder/configs.h || echo "No CYD_ lines found"

      - name: Install required libraries from GitHub
        run: |
          mkdir -p $HOME/Arduino/libraries
          cd $HOME/Arduino/libraries
          for LIB in ${{ join(matrix.board.libs, ' ') }}; do
            REPO=$(echo "$LIB" | cut -d@ -f1)
            VERSION=$(echo "$LIB" | cut -d@ -f2)
            REL_PATH="${REPO#libraries/}"
            LIB_PATH="$ESP32_MARAUDER_WORKDIR/libraries/$REL_PATH"
            LIB_DEST="$HOME/Arduino/libraries/$(basename "$REL_PATH")"
            echo "Processing: $REPO@$VERSION"
            if [[ "$REPO" == libraries/* ]]; then
              if [[ -d "$LIB_PATH" ]]; then
                echo "Copying local library from $LIB_PATH to $LIB_DEST"
                cp -r "$LIB_PATH" "$LIB_DEST"
              else
                echo "::warning::Library path '$LIB_PATH' not found. Skipping."
              fi
            else
              echo "Checking if https://github.com/$REPO.git has $VERSION..."
              if git ls-remote --tags --heads https://github.com/$REPO.git | grep -q "refs/tags/$VERSION"; then
                echo "Cloning tag $VERSION from $REPO"
                git clone --depth 1 --branch "$VERSION" "https://github.com/$REPO.git" "$LIB_DEST"
              else
                echo "::warning::Tag '$VERSION' not found for $REPO. Skipping."
              fi
            fi
          done

      - name: List installed Arduino libraries
        run: ./bin/arduino-cli lib list

      - name: List all sketches before build
        run: |
          echo "Looking for .ino files in $ESP32_MARAUDER_WORKDIR..."
          find "$ESP32_MARAUDER_WORKDIR" -type f -name "*.ino"

      - name: Compile ${{ matrix.board.name }}
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: esp32_marauder.ino
          sketch-names-find-start: esp32-marauder-src
          arduino-board-fqbn: ${{ matrix.board.fbqn }}
          extra-arduino-cli-args: "--warnings none"
          arduino-platform: esp32:esp32@2.0.10
          platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Rename binary with version and date
        run: |
          cd "$ESP32_MARAUDER_WORKDIR"
          VERSION=$(grep 'MARAUDER_VERSION' esp32_marauder/esp32_marauder.ino | cut -d '"' -f2 | tr '.' '_')
          DATE=$(date +%Y%m%d)
          BINFILE=$(find ~/.arduino15/packages/esp32/hardware/esp32/*/build -name '*.bin' | head -n1 || find esp32_marauder/build -name '*.bin' | head -n1)
          OUTFILE="esp32_marauder_${VERSION}_${DATE}_${{ matrix.board.flag }}.bin"
          cp "$BINFILE" "$OUTFILE"
          echo "OUTFILE=$OUTFILE" >> $GITHUB_ENV

      - name: Upload renamed artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTFILE }}
          path: ${{ env.OUTFILE }}
